




.build/micro-52c748a2/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/micro-52c748a2/src
	@echo [93msrc/sketch.ino[0m
	/usr/bin/ino preproc -d /home/azisi/Documents/Apps/arduino-1.0.5 -o $@ $^


all : .build/micro-52c748a2/src/sketch.cpp
	@true

