























.build/micro/Servo/Servo.o : /home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo/Servo.cpp
	@echo [93mServo/Servo.cpp[0m
	@mkdir -p .build/micro/Servo
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo/Servo.cpp
include .build/micro/Servo/Servo.d



.build/micro/Servo/libServo.a : .build/micro/Servo/Servo.o
	@echo [92mLinking libServo.a[0m
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/micro/arduino/wiring_pulse.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/micro/arduino/wiring_pulse.d

.build/micro/arduino/wiring_digital.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_digital.c
include .build/micro/arduino/wiring_digital.d

.build/micro/arduino/wiring_analog.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_analog.c
include .build/micro/arduino/wiring_analog.d

.build/micro/arduino/wiring.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/wiring.c
include .build/micro/arduino/wiring.d

.build/micro/arduino/WInterrupts.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/WInterrupts.c
include .build/micro/arduino/WInterrupts.d

.build/micro/arduino/avr-libc/realloc.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc/realloc.c
	@echo [93marduino/avr-libc/realloc.c[0m
	@mkdir -p .build/micro/arduino/avr-libc
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc/realloc.c
include .build/micro/arduino/avr-libc/realloc.d

.build/micro/arduino/avr-libc/malloc.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc/malloc.c
	@echo [93marduino/avr-libc/malloc.c[0m
	@mkdir -p .build/micro/arduino/avr-libc
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc/malloc.c
include .build/micro/arduino/avr-libc/malloc.d

.build/micro/arduino/wiring_shift.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_shift.c
include .build/micro/arduino/wiring_shift.d






.build/micro/arduino/HardwareSerial.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/micro/arduino/HardwareSerial.d

.build/micro/arduino/USBCore.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/USBCore.cpp
include .build/micro/arduino/USBCore.d

.build/micro/arduino/Print.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/Print.cpp
include .build/micro/arduino/Print.d

.build/micro/arduino/IPAddress.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/micro/arduino/IPAddress.d

.build/micro/arduino/main.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/main.cpp
include .build/micro/arduino/main.d

.build/micro/arduino/WMath.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/WMath.cpp
include .build/micro/arduino/WMath.d

.build/micro/arduino/Stream.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/Stream.cpp
include .build/micro/arduino/Stream.d

.build/micro/arduino/WString.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/WString.cpp
include .build/micro/arduino/WString.d

.build/micro/arduino/new.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/new.cpp
include .build/micro/arduino/new.d

.build/micro/arduino/HID.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/HID.cpp
include .build/micro/arduino/HID.d

.build/micro/arduino/CDC.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/CDC.cpp
include .build/micro/arduino/CDC.d

.build/micro/arduino/Tone.o : /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/micro/arduino
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/Tone.cpp
include .build/micro/arduino/Tone.d



.build/micro/arduino/libarduino.a : .build/micro/arduino/wiring_pulse.o .build/micro/arduino/wiring_digital.o .build/micro/arduino/wiring_analog.o .build/micro/arduino/wiring.o .build/micro/arduino/WInterrupts.o .build/micro/arduino/avr-libc/realloc.o .build/micro/arduino/avr-libc/malloc.o .build/micro/arduino/wiring_shift.o .build/micro/arduino/HardwareSerial.o .build/micro/arduino/USBCore.o .build/micro/arduino/Print.o .build/micro/arduino/IPAddress.o .build/micro/arduino/main.o .build/micro/arduino/WMath.o .build/micro/arduino/Stream.o .build/micro/arduino/WString.o .build/micro/arduino/new.o .build/micro/arduino/HID.o .build/micro/arduino/CDC.o .build/micro/arduino/Tone.o
	@echo [92mLinking libarduino.a[0m
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/micro/src/sketch.o : .build/micro/src/sketch.cpp
	@echo [93msrc/sketch.cpp[0m
	@mkdir -p .build/micro/src
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=105 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8037 -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/variants/micro -I/home/azisi/Documents/Apps/arduino-1.0.5/libraries/Servo -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/azisi/Documents/Apps/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions -iquote src  -o $@ -c .build/micro/src/sketch.cpp
include .build/micro/src/sketch.d







.build/micro/firmware.elf : .build/micro/src/sketch.o .build/micro/Servo/libServo.a .build/micro/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/micro/firmware.hex : .build/micro/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/home/azisi/Documents/Apps/arduino-1.0.5/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/micro/src/dependencies.d .build/micro/arduino/dependencies.d .build/micro/Servo/dependencies.d

all : .build/micro/firmware.hex
	@true

